### ISSUE TITLE
关于 nonce 字段的疑惑

### ISSUE THREAD

**Issue by FaiChou** [kazutoiris/ali_ecc#1]
项目里代码只有一次 createSession, 此时 nonce = 0. 在原帖中可以看到 nonce 刷新是随机的, 每次 `nonce++`, 将新的 signature 通过 renewSession 传给后台. nonce 的过期时间并没有发送给后台, 所以后台并不知道 nonce 是否过期. 是否可以一直使用 nonce = 0, 而不再更新 signature 值呢?

**Comment by kazutoiris** [comment]
Theoretically, the value of nonce can be reused all the time without updating it.

Also, you can always `create session` instead of `renew session`.

A test file is placed in the project that you can use to test if it is necessary to update the nonce value.

**Notice:** If it fails, try to increase the interval. It probably takes at least 0.5 seconds to 1 second.

**Comment by fs185085781** [comment]
> 项目里代码只有一次 createSession， 此时 nonce = 0.在原帖中可以看到 nonce 刷新是随机的， 每次 ， 将新的 signature 通过 renewSession 传给后台.nonce 的过期时间并没有发送给后台， 所以后台并不知道 nonce 是否过期.是否可以一直使用 nonce = 0， 而不再更新 signature 值呢？`nonce++`

试过,不行的,上一次的nonce为1的话,下次renewSession一定要用2,用1或者3的话都报{"result":false,"success":true}

**Comment by kazutoiris** [comment]
I mean if you do not refresh the nonce, the nonce can be used for 5~10 minutes, even longer. (I'm not sure if it's permanently available.)

But if you refresh the nonce manually, the original nonce will be invalidated certainly.

**Comment by eritpchy** [comment]
经测试, 如果不renew的话每次生成的sign大概只有效5-10分钟

**Comment by kazutoiris** [comment]
> 经测试, 如果不renew的话每次生成的sign大概只有效5-10分钟

Thank you for your feedback. Your feedback is very useful!
